sudo: false
language: node_js
env:
  - PUBLISH_FROM_NODE_VERSION=8.10
node_js:
  - "8.10"
  - "node"

before_install:
  - npm install -g npm@latest

install:
  - npm ci

before_script:
  - npm run build:browser

after_success:
  - npm run doc
  - ./.travis_publish
